### ISSUE TITLE
Support passing components as labels

### ISSUE THREAD

**Issue by mohitharshan123** [curtx/react-native-swipe-tabs#5]
We should be able to pass components in label array so that we can display icons instead of only strings.

**Comment by curtx** [comment]
Hi, @mohitharshan123!

Thank you for your suggestion. I will update the component so that we can add icons. I hope I will be able to publish a new version within two working days.

Thank you!

**Comment by curtx** [comment]
Hi @mohitharshan123 !

I am pleased to inform that you can pass label components into the new prop 'labelComponents' in the new version 1.1.3. Here is an example:

![image](https://github.com/curtx/react-native-swipe-tabs/assets/89903475/b3477f3a-a682-43de-a0c7-3557c6f985cb)

Please let me know if this addresses your issue.

Thank you!

**Comment by mohitharshan123** [comment]
@curtx LGTM. Thank you.

**Comment by curtx** [comment]
Since it has been fixed long ago, and no issues were reported. I am closing this issue.
